name: Tally

options:
  bundleIdPrefix: com.tally
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

targets:
  Tally:
    type: application
    platform: iOS
    sources:
      - path: Tally
    entitlements:
      path: Tally/Tally.entitlements
    settings:
      base:
        DEVELOPMENT_TEAM: "6724KRX9W7"
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        CURRENT_PROJECT_VERSION: "1"
        MARKETING_VERSION: "2.0.0"
        PRODUCT_BUNDLE_IDENTIFIER: com.tally.Tally
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
