name: Tally

options:
  bundleIdPrefix: com.yoshiki
  deploymentTarget:
    iOS: "18.5"
  xcodeVersion: "16.4"
  generateEmptyDirectories: true

targets:
  Tally:
    type: application
    platform: iOS
    sources:
      - path: Tally
    info:
      path: Tally/Info.plist
      properties:
        UIBackgroundModes:
          - remote-notification
    entitlements:
      path: Tally/Tally.entitlements
      properties:
        com.apple.developer.icloud-services:
          - CloudKit
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.yoshiki.Tally
        aps-environment: development
        com.apple.security.application-groups:
          - group.com.yoshiki.Tally
    settings:
      base:
        DEVELOPMENT_TEAM: "6724KRX9W7"
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
        ENABLE_USER_SCRIPT_SANDBOXING: YES
        DEAD_CODE_STRIPPING: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        CURRENT_PROJECT_VERSION: "1"
        MARKETING_VERSION: "2.0.0"
        PRODUCT_BUNDLE_IDENTIFIER: com.yoshiki.Tally
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
